package apps

import (
	"fmt"
	"os"
	"path/filepath"
)

// ScaffoldDemo writes a tiny runnable app into an empty workdir for
// native runtimes. It never overwrites existing source: non-empty
// directories are treated as operator-owned and left untouched.
func ScaffoldDemo(a *App) (bool, error) {
	if a == nil {
		return false, fmt.Errorf("apps: cannot scaffold nil app")
	}
	if a.WorkDir == "" {
		return false, fmt.Errorf("apps: %s: work_dir is required before scaffolding", a.Name)
	}

	files, command := demoFiles(a)
	if len(files) == 0 {
		return false, nil
	}

	if err := os.MkdirAll(a.WorkDir, 0755); err != nil {
		return false, fmt.Errorf("apps: %s: create workdir %s: %w", a.Name, a.WorkDir, err)
	}
	entries, err := os.ReadDir(a.WorkDir)
	if err != nil {
		return false, fmt.Errorf("apps: %s: read workdir %s: %w", a.Name, a.WorkDir, err)
	}
	if len(entries) > 0 {
		return false, nil
	}

	for name, content := range files {
		path := filepath.Join(a.WorkDir, name)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return false, fmt.Errorf("apps: %s: write demo file %s: %w", a.Name, path, err)
		}
	}
	if a.Command == "" && command != "" {
		a.Command = command
	}
	return true, nil
}

func demoFiles(a *App) (map[string]string, string) {
	readme := fmt.Sprintf("# %s\n\nGenerated by UWAS. Replace this demo with your application code.\n", a.Name)
	switch a.Runtime {
	case RuntimeNode:
		return map[string]string{
			"README.md": readme,
			"index.js": `const http = require('http');

const port = Number(process.env.PORT || 3000);
const appName = process.env.APP_NAME || '` + a.Name + `';

http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
  res.end(appName + ' is running on UWAS\n');
}).listen(port, '0.0.0.0', () => {
  console.log(appName + ' listening on port ' + port);
});
`,
		}, ""
	case RuntimePython:
		return map[string]string{
			"README.md": readme,
			"app.py": `import os
from http.server import BaseHTTPRequestHandler, HTTPServer


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        body = b"` + a.Name + ` is running on UWAS\n"
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "3000"))
    HTTPServer(("0.0.0.0", port), Handler).serve_forever()
`,
		}, ""
	case RuntimeRuby:
		return map[string]string{
			"README.md": readme,
			"app.rb": `require 'socket'

port = ENV.fetch('PORT', '3000').to_i
server = TCPServer.new('0.0.0.0', port)
puts '` + a.Name + ` listening on port ' + port.to_s

loop do
  client = server.accept
  body = "` + a.Name + ` is running on UWAS\n"
  client.write "HTTP/1.1 200 OK\r\n"
  client.write "Content-Type: text/plain; charset=utf-8\r\n"
  client.write "Content-Length: #{body.bytesize}\r\n"
  client.write "Connection: close\r\n\r\n"
  client.write body
  client.close
end
`,
		}, "ruby app.rb"
	case RuntimeGo:
		return map[string]string{
			"README.md": readme,
			"main.go": `package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
)

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "3000"
	}
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		fmt.Fprintln(w, "` + a.Name + ` is running on UWAS")
	})
	log.Printf("` + a.Name + ` listening on port %s", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
`,
		}, "go run main.go"
	default:
		return nil, ""
	}
}
